sudo: false
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  - '9'
  - '8'
  - '6'
branches:
  only:
    - master
    - /^greenkeeper.*$/

before_install:
  - ./scripts/run-on-node-version.sh 10 "npm install -g greenkeeper-lockfile@1"

before_script:
  - ./scripts/run-on-node-version.sh 10 "greenkeeper-lockfile-update"

after_success:
  - npm install -g travis-deploy-once
  - travis-deploy-once "npm run semantic-release"

after_script:
  - ./scripts/run-on-node-version.sh 10 "greenkeeper-lockfile-upload"
